### ISSUE TITLE
Running status indicator unreliable

### ISSUE THREAD

**Issue by mishaturnbull** [mishaturnbull/EasyService#1]
Noticed on `dradis`.  If service is started outside of the program, then program started, it reports service as stopped when it is running and visible outside program.

**Comment by mishaturnbull** [comment]
Seems to be the responsible error message:

```python
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/shared/Random Programming Shit/Python/EasyService/src/servicemgr.py", line 115, in run
    self.func()
  File "/mnt/shared/Random Programming Shit/Python/EasyService/src/servicemgr.py", line 97, in check_run
    status = parse_lsof_output(cmd.get_output()['stdout'],
  File "/mnt/shared/Random Programming Shit/Python/EasyService/src/servicemgr.py", line 141, in get_output
    out.update(returncode=self._result.returncode,
AttributeError: 'NoneType' object has no attribute 'returncode'
```

------------------------

Edit: that is not a relevant error.
